# Generated by Django 2.2.1 on 2019-05-19 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190515_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('middleName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('m_status', models.TextField(choices=[('m', 'married'), ('u', 'unmarried')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('city', models.TextField(blank=True, max_length=25)),
                ('village', models.TextField(blank=True, max_length=35)),
                ('State', models.TextField(blank=True, max_length=25)),
                ('country', models.TextField(max_length=25)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familychoice', models.CharField(choices=[('f', 'Father'), ('s', 'Mother'), ('gf', 'Grand Father'), ('gm', 'Gran Mother'), ('b', 'Brother'), ('si', 'Sister'), ('s', 'Son'), ('d', 'Daughter'), ('h', 'Husband'), ('w', 'Wife')], max_length=2)),
                ('name', models.TextField(max_length=50)),
                ('m_status', models.TextField(choices=[('m', 'married'), ('u', 'unmarried')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('qualification', models.CharField(choices=[('ugd10', 'Under Grade 10'), ('gd10', 'Grade 10'), ('gd12', 'Grade 12'), ('ba', 'Bachelors'), ('ma', 'Masters'), ('mphl', 'M.Phil'), ('phd', 'Ph.D')], max_length=4)),
                ('fieldOfStudy', models.CharField(max_length=50)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('graduated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
