# Generated by Django 2.2.1 on 2019-05-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190519_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='State',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='m_status',
            field=models.TextField(choices=[('m', 'married'), ('u', 'unmarried')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='village',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
    ]
