# Generated by Django 2.2.1 on 2019-05-19 20:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190519_1220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='education',
            managers=[
                ('objects', users.models.EducationManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='familyinfo',
            managers=[
                ('objects', users.models.FamilyInfoManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', users.models.ProfileManger()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
