# Generated by Django 2.2.1 on 2019-05-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190519_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='State',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='village',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
