# Generated by Django 2.2.1 on 2019-05-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190519_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lastName',
        ),
    ]
