# Generated by Django 2.2.1 on 2019-05-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinfo',
            name='m_status',
            field=models.CharField(choices=[('m', 'married'), ('u', 'unmarried')], max_length=1),
        ),
        migrations.AlterField(
            model_name='familyinfo',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
