# Generated by Django 2.2.1 on 2019-05-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cnic',
            field=models.IntegerField(max_length=13, null=True, unique=True),
        ),
    ]
