# Generated by Django 2.2.1 on 2019-06-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190607_0246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
