# Generated by Django 2.2.1 on 2019-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190608_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/images/empty_avatar.png', null=True, upload_to='gallery/profile_pic'),
        ),
    ]
