# Generated by Django 2.2.1 on 2019-06-17 03:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190608_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='familyinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='profile_education', to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyinfo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_family', to='users.Profile'),
            preserve_default=False,
        ),
    ]
