# Generated by Django 2.2.1 on 2019-06-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190616_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='dateFrom',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='fieldOfStudy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(choices=[('ugd10', 'Under Grade 10'), ('gd10', 'Grade 10'), ('gd12', 'Grade 12'), ('ba', 'Bachelors'), ('ma', 'Masters'), ('mphl', 'M.Phil'), ('phd', 'Ph.D')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
