# Generated by Django 2.2.1 on 2019-06-17 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190616_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinfo',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_family', to='users.Profile'),
        ),
    ]
