# Generated by Django 2.2.1 on 2019-06-17 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190617_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='familyinfo',
            name='profile',
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familyinfo',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='dateFrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='fieldOfStudy',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(choices=[('ugd10', 'Under Grade 10'), ('gd10', 'Grade 10'), ('gd12', 'Grade 12'), ('ba', 'Bachelors'), ('ma', 'Masters'), ('mphl', 'M.Phil'), ('phd', 'Ph.D')], max_length=4),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=50),
        ),
    ]
