# Generated by Django 2.2.1 on 2019-06-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190617_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(choices=[('ug10', 'Under Grade 10'), ('gd10', 'Grade 10'), ('gd12', 'Grade 12'), ('ba', 'Bachelors'), ('ma', 'Masters'), ('mphl', 'M.Phil'), ('phd', 'Ph.D')], max_length=4),
        ),
    ]
