# Generated by Django 2.2.1 on 2019-06-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20190617_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinfo',
            name='familychoice',
            field=models.CharField(choices=[('f', 'Father'), ('m', 'Mother'), ('gf', 'Grand Father'), ('gm', 'Gran Mother'), ('b', 'Brother'), ('si', 'Sister'), ('s', 'Son'), ('d', 'Daughter'), ('h', 'Husband'), ('w', 'Wife')], max_length=2),
        ),
    ]
