# Generated by Django 2.2.1 on 2019-06-18 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190617_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='followings',
        ),
        migrations.AddField(
            model_name='connection',
            name='accept_request',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='connection',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following',
                                to='users.Profile'),
        ),
    ]
