# Generated by Django 2.2.1 on 2019-06-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20190617_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.Profile'),
        ),
    ]
