# Generated by Django 2.2.1 on 2019-06-18 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20190617_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='accept_request',
        ),
        migrations.AddField(
            model_name='connection',
            name='following',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.Profile'),
        ),
    ]
